# Generated by Django 3.1.7 on 2021-02-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('sub_title', models.CharField(max_length=300, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('image', models.ImageField(upload_to='uploads/sectionsimg/')),
            ],
        ),
    ]
