# Generated by Django 3.1.7 on 2021-02-28 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_sections'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sections',
            new_name='Section',
        ),
    ]
