# Generated by Django 3.1.7 on 2021-02-28 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20210228_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='banners_category',
            field=models.ForeignKey(default=7, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.category'),
        ),
    ]
