# Generated by Django 3.1.7 on 2021-02-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_banner_banners_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='maincategory',
        ),
        migrations.AddField(
            model_name='category',
            name='subcategory',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
