# Generated by Django 3.1.7 on 2021-02-28 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20210301_0134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='maincategory',
            new_name='category',
        ),
    ]
