# Generated by Django 3.1.7 on 2021-02-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20210301_0147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='subcategory',
        ),
    ]
