# Generated by Django 3.1.7 on 2021-03-01 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_mac'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productbanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('product_subcategory', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='store.subcategory')),
            ],
        ),
    ]
