# Generated by Django 3.1.7 on 2021-03-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_productbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbanner',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/banners/productbanners'),
        ),
    ]
