# Generated by Django 3.1.7 on 2021-03-01 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_appleaccessories_applecare'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipad',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.subcategory'),
            preserve_default=False,
        ),
    ]
