# Generated by Django 3.1.7 on 2021-03-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_accessories_bose_headphones_speakers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(blank=True, default=1, max_length=500, null=True),
        ),
    ]
