# Generated by Django 3.1.7 on 2021-03-02 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_subcategory_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
    ]
