# Generated by Django 3.1.7 on 2021-03-02 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_remove_subcategory_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='product',
            name='specs',
            field=models.CharField(blank=True, default=None, max_length=5000000, null=True),
        ),
    ]
