# Generated by Django 3.1.7 on 2021-03-02 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_maincategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='maincategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.maincategory'),
        ),
    ]
