# Generated by Django 3.1.7 on 2021-03-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_auto_20210303_0524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=50)),
                ('mobilenumber', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('zip', models.IntegerField()),
                ('check', models.CharField(default='Not Choosen', max_length=15)),
            ],
        ),
    ]
