# Generated by Django 3.1.7 on 2021-03-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_auto_20210325_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(default='Cash on Delivery', max_length=30),
        ),
    ]
