# Generated by Django 3.1.7 on 2021-03-25 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_order_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='username',
        ),
    ]
