# Generated by Django 3.1.7 on 2021-03-25 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0043_remove_order_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='username',
            field=models.ForeignKey(blank=True, default='', max_length=300, on_delete=django.db.models.deletion.CASCADE, to='store.customer'),
        ),
    ]
