# Generated by Django 3.1.7 on 2021-03-25 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0047_order_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='username',
            new_name='userid',
        ),
    ]
