# Generated by Django 3.1.7 on 2021-03-25 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0051_auto_20210325_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='completed',
            new_name='status',
        ),
    ]
