# Generated by Django 5.2 on 2025-05-04 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0053_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='check',
        ),
        migrations.AddField(
            model_name='customer',
            name='status_check',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
