# Generated by Django 5.2 on 2025-05-04 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0055_alter_accessories_id_alter_appleaccessories_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='status_check',
        ),
        migrations.AddField(
            model_name='customer',
            name='agree_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobilenumber',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='zip',
            field=models.CharField(max_length=10),
        ),
    ]
